USE [BANK]
GO

CREATE TABLE ESTADO_CIVIL(
    UUID INT IDENTITY(1,1) PRIMARY KEY,
    TIPO NVARCHAR(20) NOT NULL
)
GO

Create view view_estado_civil(
	UUID,
	TIPO
) AS
SELECT
	UUID,
	TIPO
FROM
	ESTADO_CIVIL
GO


INSERT INTO ESTADO_CIVIL VALUES ('Soltero');
INSERT INTO ESTADO_CIVIL VALUES ('Casado');
INSERT INTO ESTADO_CIVIL VALUES ('Union Libre');
INSERT INTO ESTADO_CIVIL VALUES ('Viudo');