USE [BANK]
GO

CREATE TABLE [dbo].[ESTADO_OPERACION](
	UUID INT IDENTITY(1,1) NOT NULL,
	Nombre NVARCHAR(10) NOT NULL,
 	CONSTRAINT [PK_ESTADO_OPERACION] PRIMARY KEY CLUSTERED (UUID ASC) ON [PRIMARY]
) ON [PRIMARY]--Luego se especifica a que FG ir� segun modelo f�sico
GO

Create view view_estado_operacion(
	UUID,
	Nombre
) AS
SELECT
	UUID,
	Nombre
FROM
	ESTADO_OPERACION
GO

--Registros
INSERT INTO ESTADO_OPERACION VALUES ('Activo');
INSERT INTO ESTADO_OPERACION VALUES ('Inactivo');
INSERT INTO ESTADO_OPERACION VALUES ('Pendiente');