USE [BANK]
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Garantia](
	[UUID] [int] IDENTITY(1,1) NOT NULL,
	[Descripcion] NVARCHAR (50) NOT NULL,
 	CONSTRAINT [PK_Garantia] PRIMARY KEY CLUSTERED 
(
	[UUID] ASC
)	WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) 	ON [PRIMARY]
GO

Create view view_garantia(
	UUID,
	Descripcion
) AS
SELECT
	UUID,
	Descripcion
FROM
	Garantia
GO


--Ejemplo 
INSERT INTO GARANTIA VALUES ('Terreno 1')
INSERT INTO GARANTIA VALUES ('Vehiculo 2')
INSERT INTO GARANTIA VALUES ('Casa 3')
INSERT INTO GARANTIA VALUES ('Terreno 4')
INSERT INTO GARANTIA VALUES ('Casa 5')
INSERT INTO GARANTIA VALUES ('Vehiculo 6')
INSERT INTO GARANTIA VALUES ('Terreno 7')
INSERT INTO GARANTIA VALUES ('Terreno 8')
INSERT INTO GARANTIA VALUES ('Terreno 9')
INSERT INTO GARANTIA VALUES ('Vehiculo 10')
INSERT INTO GARANTIA VALUES ('Vehiculo 11')
INSERT INTO GARANTIA VALUES ('Vehiculo 12')
INSERT INTO GARANTIA VALUES ('Terreno 13')
INSERT INTO GARANTIA VALUES ('Vehiculo 14')
INSERT INTO GARANTIA VALUES ('Casa 15')
INSERT INTO GARANTIA VALUES ('Casa 16')
INSERT INTO GARANTIA VALUES ('Vehiculo 17')
INSERT INTO GARANTIA VALUES ('Vehiculo 18')
INSERT INTO GARANTIA VALUES ('Terreno 19')
INSERT INTO GARANTIA VALUES ('Vehiculo 20')
INSERT INTO GARANTIA VALUES ('Vehiculo 21')
INSERT INTO GARANTIA VALUES ('Terreno 22')
INSERT INTO GARANTIA VALUES ('Vehiculo 23')
INSERT INTO GARANTIA VALUES ('Vehiculo 24')
INSERT INTO GARANTIA VALUES ('Casa 25')
INSERT INTO GARANTIA VALUES ('Terreno 26')
INSERT INTO GARANTIA VALUES ('Terreno 27')
INSERT INTO GARANTIA VALUES ('Vehiculo 28')
INSERT INTO GARANTIA VALUES ('Casa 29')
INSERT INTO GARANTIA VALUES ('Casa 30')
INSERT INTO GARANTIA VALUES ('Vehiculo 31')
INSERT INTO GARANTIA VALUES ('Vehiculo 32')
INSERT INTO GARANTIA VALUES ('Vehiculo 33')
INSERT INTO GARANTIA VALUES ('Casa 34')
INSERT INTO GARANTIA VALUES ('Casa 35')
INSERT INTO GARANTIA VALUES ('Casa 36')
INSERT INTO GARANTIA VALUES ('Vehiculo 37')
INSERT INTO GARANTIA VALUES ('Vehiculo 38')
INSERT INTO GARANTIA VALUES ('Casa 39')
INSERT INTO GARANTIA VALUES ('Casa 40')
INSERT INTO GARANTIA VALUES ('Vehiculo 41')
INSERT INTO GARANTIA VALUES ('Casa 42')
INSERT INTO GARANTIA VALUES ('Vehiculo 43')
INSERT INTO GARANTIA VALUES ('Terreno 44')
INSERT INTO GARANTIA VALUES ('Terreno 45')
INSERT INTO GARANTIA VALUES ('Casa 46')
INSERT INTO GARANTIA VALUES ('Terreno 47')
INSERT INTO GARANTIA VALUES ('Vehiculo 48')