USE [BANK]
GO

CREATE TABLE [dbo].[Moneda](
	[UUID] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] NVARCHAR(50) NOT NULL,
	[Codigo] NVARCHAR(3) NOT NULL
 CONSTRAINT [PK_Moneda] PRIMARY KEY CLUSTERED 
(
	[UUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] --Luego se especifica a que FG ir� segun modelo f�sico
GO

--Ejemplos
Insert into Moneda Values('UAE Dirham','AED')
Insert into Moneda Values('Afghani','AFN')
Insert into Moneda Values('Lek','ALL')
Insert into Moneda Values('Armenian Dram','AMD')
Insert into Moneda Values('Netherlands Antillean Guilder','ANG')
Insert into Moneda Values('Kwanza','AOA')
Insert into Moneda Values('Argentine Peso','ARS')
Insert into Moneda Values('Australian Dollar','AUD')
Insert into Moneda Values('Aruban Florin','AWG')
Insert into Moneda Values('Azerbaijanian Manat','AZN')
Insert into Moneda Values('Convertible Mark','BAM')
Insert into Moneda Values('Barbados Dollar','BBD')
Insert into Moneda Values('Taka','BDT')
Insert into Moneda Values('Bulgarian Lev','BGN')
Insert into Moneda Values('Bahraini Dinar','BHD')
Insert into Moneda Values('Burundi Franc','BIF')
Insert into Moneda Values('Bermudian Dollar','BMD')
Insert into Moneda Values('Brunei Dollar','BND')
Insert into Moneda Values('Boliviano','BOB')
Insert into Moneda Values('Mvdol','BOV')
Insert into Moneda Values('Brazilian Real','BRL')
Insert into Moneda Values('Bahamian Dollar','BSD')
Insert into Moneda Values('Ngultrum','BTN')
Insert into Moneda Values('Pula','BWP')
Insert into Moneda Values('Belarussian Ruble','BYN')
Insert into Moneda Values('Belize Dollar','BZD')
Insert into Moneda Values('Canadian Dollar','CAD')
Insert into Moneda Values('Congolese Franc','CDF')
Insert into Moneda Values('WIR Euro','CHE')
Insert into Moneda Values('Swiss Franc','CHF')
Insert into Moneda Values('WIR Franc','CHW')
Insert into Moneda Values('Unidad de Fomento','CLF')
Insert into Moneda Values('Chilean Peso','CLP')
Insert into Moneda Values('Yuan Renminbi','CNY')
Insert into Moneda Values('Colombian Peso','COP')
Insert into Moneda Values('Unidad de Valor Real','COU')
Insert into Moneda Values('Costa Rican Colon','CRC')
Insert into Moneda Values('Peso Convertible','CUC')
Insert into Moneda Values('Cuban Peso','CUP')
Insert into Moneda Values('Cabo Verde Escudo','CVE')
Insert into Moneda Values('Czech Koruna','CZK')
Insert into Moneda Values('Djibouti Franc','DJF')
Insert into Moneda Values('Danish Krone','DKK')
Insert into Moneda Values('Dominican Peso','DOP')
Insert into Moneda Values('Algerian Dinar','DZD')
Insert into Moneda Values('Egyptian Pound','EGP')
Insert into Moneda Values('Nakfa','ERN')
Insert into Moneda Values('Ethiopian Birr','ETB')
Insert into Moneda Values('Euro','EUR')
Insert into Moneda Values('Fiji Dollar','FJD')
Insert into Moneda Values('Falkland Islands Pound','FKP')
Insert into Moneda Values('Pound Sterling','GBP')
Insert into Moneda Values('Lari','GEL')
Insert into Moneda Values('Ghana Cedi','GHS')
Insert into Moneda Values('Gibraltar Pound','GIP')
Insert into Moneda Values('Dalasi','GMD')
Insert into Moneda Values('Guinea Franc','GNF')
Insert into Moneda Values('Quetzal','GTQ')
Insert into Moneda Values('Guyana Dollar','GYD')
Insert into Moneda Values('Hong Kong Dollar','HKD')
Insert into Moneda Values('Lempira','HNL')
Insert into Moneda Values('Kuna','HRK')
Insert into Moneda Values('Gourde','HTG')
Insert into Moneda Values('Forint','HUF')
Insert into Moneda Values('Rupiah','IDR')
Insert into Moneda Values('New Israeli Sheqel','ILS')
Insert into Moneda Values('Indian Rupee','INR')
Insert into Moneda Values('Iraqi Dinar','IQD')
Insert into Moneda Values('Iranian Rial','IRR')
Insert into Moneda Values('Iceland Krona','ISK')
Insert into Moneda Values('Jamaican Dollar','JMD')
Insert into Moneda Values('Jordanian Dinar','JOD')
Insert into Moneda Values('Yen','JPY')
Insert into Moneda Values('Kenyan Shilling','KES')
Insert into Moneda Values('Som','KGS')
Insert into Moneda Values('Riel','KHR')
Insert into Moneda Values('Comoro Franc','KMF')
Insert into Moneda Values('North Korean Won','KPW')
Insert into Moneda Values('Won','KRW')
Insert into Moneda Values('Kuwaiti Dinar','KWD')
Insert into Moneda Values('Cayman Islands Dollar','KYD')
Insert into Moneda Values('Tenge','KZT')
Insert into Moneda Values('Kip','LAK')
Insert into Moneda Values('Lebanese Pound','LBP')
Insert into Moneda Values('Sri Lanka Rupee','LKR')
Insert into Moneda Values('Liberian Dollar','LRD')
Insert into Moneda Values('Loti','LSL')
Insert into Moneda Values('Libyan Dinar','LYD')
Insert into Moneda Values('Moroccan Dirham','MAD')
Insert into Moneda Values('Moldovan Leu','MDL')
Insert into Moneda Values('Malagasy Ariary','MGA')
Insert into Moneda Values('Denar','MKD')
Insert into Moneda Values('Kyat','MMK')
Insert into Moneda Values('Tugrik','MNT')
Insert into Moneda Values('Pataca','MOP')
Insert into Moneda Values('Ouguiya','MRU')
Insert into Moneda Values('Mauritius Rupee','MUR')
Insert into Moneda Values('Rufiyaa','MVR')
Insert into Moneda Values('Kwacha','MWK')
Insert into Moneda Values('Mexican Peso','MXN')
Insert into Moneda Values('Mexican Unidad de Inversion (UDI)','MXV')
Insert into Moneda Values('Malaysian Ringgit','MYR')
Insert into Moneda Values('Mozambique Metical','MZN')
Insert into Moneda Values('Namibia Dollar','NAD')
Insert into Moneda Values('Naira','NGN')
Insert into Moneda Values('Cordoba Oro','NIO')
Insert into Moneda Values('Norwegian Krone','NOK')
Insert into Moneda Values('Nepalese Rupee','NPR')
Insert into Moneda Values('New Zealand Dollar','NZD')
Insert into Moneda Values('Rial Omani','OMR')
Insert into Moneda Values('Balboa','PAB')
Insert into Moneda Values('Nuevo Sol','PEN')
Insert into Moneda Values('Kina','PGK')
Insert into Moneda Values('Philippine Peso','PHP')
Insert into Moneda Values('Pakistan Rupee','PKR')
Insert into Moneda Values('Zloty','PLN')
Insert into Moneda Values('Guarani','PYG')
Insert into Moneda Values('Qatari Rial','QAR')
Insert into Moneda Values('Romanian Leu','RON')
Insert into Moneda Values('Serbian Dinar','RSD')
Insert into Moneda Values('Russian Ruble','RUB')
Insert into Moneda Values('Rwanda Franc','RWF')
Insert into Moneda Values('Saudi Riyal','SAR')
Insert into Moneda Values('Solomon Islands Dollar','SBD')
Insert into Moneda Values('Seychelles Rupee','SCR')
Insert into Moneda Values('Sudanese Pound','SDG')
Insert into Moneda Values('Swedish Krona','SEK')
Insert into Moneda Values('Singapore Dollar','SGD')
Insert into Moneda Values('Saint Helena Pound','SHP')
Insert into Moneda Values('Leone','SLL')
Insert into Moneda Values('Somali Shilling','SOS')
Insert into Moneda Values('Surinam Dollar','SRD')
Insert into Moneda Values('South Sudanese Pound','SSP')
Insert into Moneda Values('Dobra','STN')
Insert into Moneda Values('El Salvador Colon','SVC')
Insert into Moneda Values('Syrian Pound','SYP')
Insert into Moneda Values('Lilangeni','SZL')
Insert into Moneda Values('Baht','THB')
Insert into Moneda Values('Somoni','TJS')
Insert into Moneda Values('Turkmenistan New Manat','TMT')
Insert into Moneda Values('Tunisian Dinar','TND')
Insert into Moneda Values('Pa’anga','TOP')
Insert into Moneda Values('Turkish Lira','TRY')
Insert into Moneda Values('Trinidad and Tobago Dollar','TTD')
Insert into Moneda Values('New Taiwan Dollar','TWD')
Insert into Moneda Values('Tanzanian Shilling','TZS')
Insert into Moneda Values('Hryvnia','UAH')
Insert into Moneda Values('Uganda Shilling','UGX')
Insert into Moneda Values('US Dollar','USD')
Insert into Moneda Values('US Dollar (Next day)','USN')
Insert into Moneda Values('Uruguay Peso en Unidades Indexadas (URUIURUI)','UYI')
Insert into Moneda Values('Peso Uruguayo','UYU')
Insert into Moneda Values('Uzbekistan Sum','UZS')
Insert into Moneda Values('Bolivar','VEF')
Insert into Moneda Values('Dong','VND')
Insert into Moneda Values('Vatu','VUV')
Insert into Moneda Values('Tala','WST')
Insert into Moneda Values('CFA Franc BEAC','XAF')
Insert into Moneda Values('East Caribbean Dollar','XCD')
Insert into Moneda Values('SDR (Special Drawing Right)','XDR')
Insert into Moneda Values('CFA Franc BCEAO','XOF')
Insert into Moneda Values('CFP Franc','XPF')
Insert into Moneda Values('Sucre','XSU')
Insert into Moneda Values('ADB Unit of Account','XUA')
Insert into Moneda Values('Yemeni Rial','YER')
Insert into Moneda Values('Rand','ZAR')
Insert into Moneda Values('Zambian Kwacha','ZMW')
Insert into Moneda Values('Zimbabwe Dollar','ZWL')