USE [BANK]
GO

CREATE TABLE OCUPACION(
    UUID INT IDENTITY(1,1) PRIMARY KEY,
    TIPO NVARCHAR(100) NOT NULL
)

INSERT INTO OCUPACION VALUES('Acomodador (cines, teatros, etc.)');
INSERT INTO OCUPACION VALUES('Acompañante en buseta escolar');
INSERT INTO OCUPACION VALUES('Agente de Aduana o Vapores');
INSERT INTO OCUPACION VALUES('Agente de Ventas');
INSERT INTO OCUPACION VALUES('Albañil');
INSERT INTO OCUPACION VALUES('Alistador Automotriz (lijador)');
INSERT INTO OCUPACION VALUES('Analista de Crédito');
INSERT INTO OCUPACION VALUES('Animador de Eventos');
INSERT INTO OCUPACION VALUES('Aplanchador (plancha tipo casera)');
INSERT INTO OCUPACION VALUES('Aplanchador con Equipo de Vapor');
INSERT INTO OCUPACION VALUES('Asistente de Abogacía');
INSERT INTO OCUPACION VALUES('Asistente de Consultorio Médico');
INSERT INTO OCUPACION VALUES('Asist. Domicilio/Ancianos');
INSERT INTO OCUPACION VALUES('(cuidados especiales)');
INSERT INTO OCUPACION VALUES('Auxiliar Agente de Aduana, Vapores');
INSERT INTO OCUPACION VALUES('Auxiliar de Contabilidad');
INSERT INTO OCUPACION VALUES('Auxiliar Dental');
INSERT INTO OCUPACION VALUES('Ayudante de Cocina');
INSERT INTO OCUPACION VALUES('Ayudante de Mecánico general');
INSERT INTO OCUPACION VALUES('Ayudante de Operario, Construcción');
INSERT INTO OCUPACION VALUES('Bachiller Universitario');
INSERT INTO OCUPACION VALUES('Baqueano');
INSERT INTO OCUPACION VALUES('Barbero');
INSERT INTO OCUPACION VALUES('Barista');
INSERT INTO OCUPACION VALUES('Bartender (Coctelera)');
INSERT INTO OCUPACION VALUES('Bodeguero (Encargado)');
INSERT INTO OCUPACION VALUES('Bodeguero (Peón)');
INSERT INTO OCUPACION VALUES('Cajero');
INSERT INTO OCUPACION VALUES('Cajista de Artes Gráficas');
INSERT INTO OCUPACION VALUES('Camarógrafo de Prensa');
INSERT INTO OCUPACION VALUES('Cantante de Música Popular');
INSERT INTO OCUPACION VALUES('Cantinero');
INSERT INTO OCUPACION VALUES('Capitán de Embarcación');
INSERT INTO OCUPACION VALUES('Carnicero Empleado Despacho');
INSERT INTO OCUPACION VALUES('Carnicero Destazador');
INSERT INTO OCUPACION VALUES('Carpintero');
INSERT INTO OCUPACION VALUES('Catador (café, vinos, otros)');
INSERT INTO OCUPACION VALUES('Cerrajero');
INSERT INTO OCUPACION VALUES('Chapulinero');
INSERT INTO OCUPACION VALUES('Chequeador Agenc Aduana, Vapor.');
INSERT INTO OCUPACION VALUES('Chequeador de Buses');
INSERT INTO OCUPACION VALUES('Chofer de Bus (no cobrador)');
INSERT INTO OCUPACION VALUES('Chofer de Tráiler');
INSERT INTO OCUPACION VALUES('Chofer de Vehículo Liviano');
INSERT INTO OCUPACION VALUES('Chofer de Vehículo Pesado');
INSERT INTO OCUPACION VALUES('Chofer Microbús (menos de11pasaj.)');
INSERT INTO OCUPACION VALUES('Chofer-Cobrador de Bus');
INSERT INTO OCUPACION VALUES('Cobrador de Buses');
INSERT INTO OCUPACION VALUES('Cobrador');
INSERT INTO OCUPACION VALUES('Cocinero');
INSERT INTO OCUPACION VALUES('Confección Muestras de Ropa');
INSERT INTO OCUPACION VALUES('Conserje');
INSERT INTO OCUPACION VALUES('Contador Privado');
INSERT INTO OCUPACION VALUES('Contador Privado');
INSERT INTO OCUPACION VALUES('Contador Privado');
INSERT INTO OCUPACION VALUES('Contador Privado');
INSERT INTO OCUPACION VALUES('Cortador de tela');
INSERT INTO OCUPACION VALUES('Cosedor Piezas /Prendas a Máquina');
INSERT INTO OCUPACION VALUES('Costurera (Modista)');
INSERT INTO OCUPACION VALUES('Counter (Vendedor de Pasajes)');
INSERT INTO OCUPACION VALUES('Dealer (Distribuidor de cartas)');
INSERT INTO OCUPACION VALUES('Demostrador(Display)');
INSERT INTO OCUPACION VALUES('Demostrador-Vendedor');
INSERT INTO OCUPACION VALUES('Dependiente');
INSERT INTO OCUPACION VALUES('Despachador Agencia Aduana, Vapores');
INSERT INTO OCUPACION VALUES('Diagramador en Artes Gráficas');
INSERT INTO OCUPACION VALUES('Dibujante en Artes Gráficas');
INSERT INTO OCUPACION VALUES('Dibujante de Ingeniería, Arquitectura');
INSERT INTO OCUPACION VALUES('Digitador');
INSERT INTO OCUPACION VALUES('Diplomado Para universitario');
INSERT INTO OCUPACION VALUES('Diplomado Universitario');
INSERT INTO OCUPACION VALUES('Ebanista');
INSERT INTO OCUPACION VALUES('Educador Aspirante sin Título');
INSERT INTO OCUPACION VALUES('Electricista');
INSERT INTO OCUPACION VALUES('Electromecánico');
INSERT INTO OCUPACION VALUES('Empacador; Etiquetador');
INSERT INTO OCUPACION VALUES('Empleado de Despacho');
INSERT INTO OCUPACION VALUES('Empleada Doméstica');
INSERT INTO OCUPACION VALUES('Encargado (indica acomodo parqueo)');
INSERT INTO OCUPACION VALUES('Encargado de Limpieza en GeneralG');
INSERT INTO OCUPACION VALUES('Encargado de Limpieza en Piscinas');
INSERT INTO OCUPACION VALUES('Enc. Mantenim. Correctivo Cómputo');
INSERT INTO OCUPACION VALUES('Enc. Mantenim. Preventivo Cómputo');
INSERT INTO OCUPACION VALUES('Encargado de poner Discos (Disjokey)');
INSERT INTO OCUPACION VALUES('Encargado de Cámaras Frigoríficas');
INSERT INTO OCUPACION VALUES('Encargado Mantenimiento Edificios');
INSERT INTO OCUPACION VALUES('Encerador de Carros');
INSERT INTO OCUPACION VALUES('Encuadernador - Empastador');
INSERT INTO OCUPACION VALUES('Encuadernador en Fino');
INSERT INTO OCUPACION VALUES('Encuadernador en Rústica');
INSERT INTO OCUPACION VALUES('Encuestador');
INSERT INTO OCUPACION VALUES('Enderezador Automotriz');
INSERT INTO OCUPACION VALUES('Engrasador de Autos');
INSERT INTO OCUPACION VALUES('Ensamblador de Computadoras');
INSERT INTO OCUPACION VALUES('Envasador Manual');
INSERT INTO OCUPACION VALUES('Esparcidor de Plaguicidas');
INSERT INTO OCUPACION VALUES('Estampador en Textil (Serigrafía)');
INSERT INTO OCUPACION VALUES('Esteticista');
INSERT INTO OCUPACION VALUES('Estibador por Kilo de frutas y vegetales');
INSERT INTO OCUPACION VALUES('Estibador por Movimiento');
INSERT INTO OCUPACION VALUES('Estibador por Tonelada');
INSERT INTO OCUPACION VALUES('Estilista');
INSERT INTO OCUPACION VALUES('Florista');
INSERT INTO OCUPACION VALUES('Fontanero');
INSERT INTO OCUPACION VALUES('Fotocopiador (Centro fotocopiado)');
INSERT INTO OCUPACION VALUES('Fotógrafo de Prensa');
INSERT INTO OCUPACION VALUES('Fotomecánico de Artes Gráficas');
INSERT INTO OCUPACION VALUES('Fotomontador (Artes Gráficas)');
INSERT INTO OCUPACION VALUES('Fresador (Metalmecánica)');
INSERT INTO OCUPACION VALUES('Fumigador (Doméstica)');
INSERT INTO OCUPACION VALUES('Fundidor');
INSERT INTO OCUPACION VALUES('Futbolista Primera División');
INSERT INTO OCUPACION VALUES('Futbolista Segunda División');
INSERT INTO OCUPACION VALUES('Gondolero');
INSERT INTO OCUPACION VALUES('Graduado del INA');
INSERT INTO OCUPACION VALUES('Guarda');
INSERT INTO OCUPACION VALUES('Guarda Custodio Valores-PortavaloresG');
INSERT INTO OCUPACION VALUES('Guía Turístico');
INSERT INTO OCUPACION VALUES('Guillotinista (Guillotina Eléctrica)');
INSERT INTO OCUPACION VALUES('Guillotinista (Electrónica programable)');
INSERT INTO OCUPACION VALUES('Hojalatero');
INSERT INTO OCUPACION VALUES('Horneador de alimentos');
INSERT INTO OCUPACION VALUES('Instructor de Bailes Populares');
INSERT INTO OCUPACION VALUES('Jardinero (Crear Jardines)');
INSERT INTO OCUPACION VALUES('Jefe de Cocina (Chef)');
INSERT INTO OCUPACION VALUES('Jefe de Saloneros (Maitre)');
INSERT INTO OCUPACION VALUES('Joyero');
INSERT INTO OCUPACION VALUES('Laboratorista Civil');
INSERT INTO OCUPACION VALUES('Laboratorista Clínico');
INSERT INTO OCUPACION VALUES('Laqueador (Muebles y Similares)');
INSERT INTO OCUPACION VALUES('Lavador de Cabello');
INSERT INTO OCUPACION VALUES('Lavador de Carros');
INSERT INTO OCUPACION VALUES('Levantador de Texto (Artes Gráficas)');
INSERT INTO OCUPACION VALUES('Licenciado Universitario');
INSERT INTO OCUPACION VALUES('Limpiador de Tanques Sépticos');
INSERT INTO OCUPACION VALUES('Linotipista (Artes Gráficas)');
INSERT INTO OCUPACION VALUES('Liquidador Agencia Aduana, Vapores');
INSERT INTO OCUPACION VALUES('Llantero');
INSERT INTO OCUPACION VALUES('Locutor de Radioemisora');
INSERT INTO OCUPACION VALUES('Locutor de Televisión');
INSERT INTO OCUPACION VALUES('Luminotécnico TV');
INSERT INTO OCUPACION VALUES('Maestro de Obras (Construcción)');
INSERT INTO OCUPACION VALUES('Manicurista; Maquilladora');
INSERT INTO OCUPACION VALUES('Maquinista de Embarcaciones');
INSERT INTO OCUPACION VALUES('Marinero');
INSERT INTO OCUPACION VALUES('Masajista');
INSERT INTO OCUPACION VALUES('Mecánico Calderas (mantenimiento).');
INSERT INTO OCUPACION VALUES('Mecánico General');
INSERT INTO OCUPACION VALUES('Mecánico Precisión');
INSERT INTO OCUPACION VALUES('Mecánico Máquinas de Coser Industrial');
INSERT INTO OCUPACION VALUES('Mecánico de Máquinas de hacer Telas');
INSERT INTO OCUPACION VALUES('Mensajero');
INSERT INTO OCUPACION VALUES('Misceláneo');
INSERT INTO OCUPACION VALUES('Misceláneo en Hogares Tercera Edad');
INSERT INTO OCUPACION VALUES('Monitoreador de cámaras de videoG');
INSERT INTO OCUPACION VALUES('Montacarguista');
INSERT INTO OCUPACION VALUES('Mucama');
INSERT INTO OCUPACION VALUES('Musicalizador en Radioemisoras');
INSERT INTO OCUPACION VALUES('Niñera, excepto en el Hogar del Niño');
INSERT INTO OCUPACION VALUES('Niñera en el Hogar del Niño');
INSERT INTO OCUPACION VALUES('(Servicio Doméstico)');
INSERT INTO OCUPACION VALUES('Oficial de Mesa (panadería)');
INSERT INTO OCUPACION VALUES('Oficinista (General)');
INSERT INTO OCUPACION VALUES('Operador de Cabina de Radioemisora');
INSERT INTO OCUPACION VALUES('Operador de "Araña" (Serigrafía)');
INSERT INTO OCUPACION VALUES('Operador de Carrusel');
INSERT INTO OCUPACION VALUES('Operador de Caldera');
INSERT INTO OCUPACION VALUES('Operador de Computación');
INSERT INTO OCUPACION VALUES('Operador de Draga');
INSERT INTO OCUPACION VALUES('Operador de Grúa Estacionaria');
INSERT INTO OCUPACION VALUES('Operador de Maquinaria Pesada');
INSERT INTO OCUPACION VALUES('Operador de Planta Transm. Radio');
INSERT INTO OCUPACION VALUES('Operador de Prensa Rotativa');
INSERT INTO OCUPACION VALUES('Operador de Radio-Taxi');
INSERT INTO OCUPACION VALUES('Operador de Escogedoras de Café');
INSERT INTO OCUPACION VALUES('Operador Escáner separador colores');
INSERT INTO OCUPACION VALUES('Operario en Construcción');
INSERT INTO OCUPACION VALUES('Operario de Talleres Dentales');
INSERT INTO OCUPACION VALUES('Ordeñador a Mano');
INSERT INTO OCUPACION VALUES('Panadero');
INSERT INTO OCUPACION VALUES('Parrillero');
INSERT INTO OCUPACION VALUES('Pastelero');
INSERT INTO OCUPACION VALUES('Pedimentador Aduana, Vapores');
INSERT INTO OCUPACION VALUES('Peinadora');
INSERT INTO OCUPACION VALUES('Peluquero / Estilista Canino');
INSERT INTO OCUPACION VALUES('Peón Agrícola');
INSERT INTO OCUPACION VALUES('Peón de Bodegas Frías');
INSERT INTO OCUPACION VALUES('Peón de Camión Distribuidor');
INSERT INTO OCUPACION VALUES('Peón de Carga y Descarga');
INSERT INTO OCUPACION VALUES('Peón de Construcción');
INSERT INTO OCUPACION VALUES('Peón de Jardín');
INSERT INTO OCUPACION VALUES('Peón en General');
INSERT INTO OCUPACION VALUES('Periodista');
INSERT INTO OCUPACION VALUES('Periodista');
INSERT INTO OCUPACION VALUES('Pilero (Lavador de Platos)');
INSERT INTO OCUPACION VALUES('Pintor Automotriz');
INSERT INTO OCUPACION VALUES('Pintor de Brocha Gorda');
INSERT INTO OCUPACION VALUES('Pistero');
INSERT INTO OCUPACION VALUES('Pizzero (Cocina Pizzas Preparadas)');
INSERT INTO OCUPACION VALUES('Portero');
INSERT INTO OCUPACION VALUES('Prensista de Artes Gráficas');
INSERT INTO OCUPACION VALUES('Preparador documentos, Ag. Aduana');
INSERT INTO OCUPACION VALUES('Programador de Computación');
INSERT INTO OCUPACION VALUES('Programador en Radioemisoras');
INSERT INTO OCUPACION VALUES('Proveedor');
INSERT INTO OCUPACION VALUES('Quemador de Marcos (Serigrafía)');
INSERT INTO OCUPACION VALUES('Quemador de Planchas');
INSERT INTO OCUPACION VALUES('Recamarera');
INSERT INTO OCUPACION VALUES('Recepcionista');
INSERT INTO OCUPACION VALUES('Recibidor de docu, Ag. Aduana');
INSERT INTO OCUPACION VALUES('Recolectores de Café Cajuela');
INSERT INTO OCUPACION VALUES('Recolectores de Coyol');
INSERT INTO OCUPACION VALUES('Relojero');
INSERT INTO OCUPACION VALUES('Repartidor de Cargas Livianas');
INSERT INTO OCUPACION VALUES('Repartidor-Propagandista');
INSERT INTO OCUPACION VALUES('Repostero');
INSERT INTO OCUPACION VALUES('Sabanero');
INSERT INTO OCUPACION VALUES('Salonero');
INSERT INTO OCUPACION VALUES('Sastre (Prendas a la Medida)');
INSERT INTO OCUPACION VALUES('Secretaria');
INSERT INTO OCUPACION VALUES('Secretaria');
INSERT INTO OCUPACION VALUES('Secretaria');
INSERT INTO OCUPACION VALUES('Secretaria');
INSERT INTO OCUPACION VALUES('Secretaria');
INSERT INTO OCUPACION VALUES('Sellista (Artes Gráficas)');
INSERT INTO OCUPACION VALUES('Servicio Doméstico');
INSERT INTO OCUPACION VALUES('Soldador (Soldaduras Especiales)');
INSERT INTO OCUPACION VALUES('Soldador en General');
INSERT INTO OCUPACION VALUES('Tapicero');
INSERT INTO OCUPACION VALUES('Tatuador');
INSERT INTO OCUPACION VALUES('Taxista');
INSERT INTO OCUPACION VALUES('Técnico de Educación Superior');
INSERT INTO OCUPACION VALUES('Técnico en Aire Acondicionado');
INSERT INTO OCUPACION VALUES('Técnico en Aparatos Ortopédicos');
INSERT INTO OCUPACION VALUES('Técnico en Lentes de Contacto');
INSERT INTO OCUPACION VALUES('Téc. Refrigeración Doméstica-Indus.');
INSERT INTO OCUPACION VALUES('Técnico en Registros Médicos');
INSERT INTO OCUPACION VALUES('Técnico Máq. Coser Ind. Especiales');
INSERT INTO OCUPACION VALUES('Técnico Medio Educ. Diversificada');
INSERT INTO OCUPACION VALUES('Técnico Reparación Audio y Video');
INSERT INTO OCUPACION VALUES('Técnicos en Salud');
INSERT INTO OCUPACION VALUES('Tejedora Manual de Prendas, Muebles');
INSERT INTO OCUPACION VALUES('Telefonista');
INSERT INTO OCUPACION VALUES('Tornero en Madera');
INSERT INTO OCUPACION VALUES('Tornero en Metal');
INSERT INTO OCUPACION VALUES('Tractorista (Oruga o Llanta)');
INSERT INTO OCUPACION VALUES('Tramitador - Abridor Aduanal');
INSERT INTO OCUPACION VALUES('Vagonetero');
INSERT INTO OCUPACION VALUES('Verdulero');
INSERT INTO OCUPACION VALUES('Zapatero');