USE [BANK]
GO

CREATE TABLE ROL_PERSONA(
    UUID INT IDENTITY(1,1) PRIMARY KEY,
    DESCRIPCION NVARCHAR(20) NOT NULL
)
GO

Create view view_rol_persona(
	UUID,
	DESCRIPCION
) AS
SELECT
	UUID,
	DESCRIPCION
FROM
	ROL_PERSONA
GO

INSERT INTO ROL_PERSONA VALUES('CLIENTE');
INSERT INTO ROL_PERSONA VALUES('EMPLEADO');
INSERT INTO ROL_PERSONA VALUES('ABOGADO NOTARIO');
INSERT INTO ROL_PERSONA VALUES('CLIENTE');
