USE [BANK]
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Tipo_operacion](
	[UUID] INT IDENTITY(1,1) NOT NULL,
	[Nombre] NVARCHAR(20) NOT NULL
 	CONSTRAINT [PK_Tipo_operacion] PRIMARY KEY CLUSTERED 
(
	[UUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


--Ejemplo
INSERT INTO Tipo_operacion VALUES ('Ingreso');
INSERT INTO Tipo_operacion VALUES ('Egreso');


