USE [BANK]
GO

CREATE TABLE [dbo].[Geografia](
	UUID INT IDENTITY(1,1) NOT NULL,
	TIPO_GEOGRAFIA INT NOT NULL REFERENCES Tipo_geografia(UUID),
	NOMBRE NVARCHAR(50) NOT NULL,
    PADRE INT NULL REFERENCES Geografia(UUID),
    CONSTRAINT [PK_Geografia] PRIMARY KEY CLUSTERED ([UUID] ASC) ON [PRIMARY]
) ON [PRIMARY] --Luego se especifica a que FG ir� segun modelo f�sico
GO

--Ejemplo
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (1, 'Costa Rica', null);

INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (2, 'Guanacaste', 1);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (2, 'Alajuela', 1);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (2, 'Heredia', 1);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (2, 'Limon', 1);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (2, 'Punteras', 1);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (2, 'San Jose', 1);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (2, 'Cartago', 1);

INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Liberia', 2);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Nicoya', 2);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Santa Cruz', 2);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Bagaces', 2);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Filadelfia', 2);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Canas', 2);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Las Juntas', 2);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Tilaran', 2);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Carmona', 2);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'La Cruz', 2);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Hojancha', 2);

INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Alajuela',3);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'San Ramon',3);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Grecia',3);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'San Mateo',3);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Atenas',3);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Naranjo',3);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Palmares',3);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Poas',3);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Orotina',3);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'San Carlos',3);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Zarcero',3);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Sarchi',3);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Upala',3);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Los Chiles',3);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Guatuso',3);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Rio Cuarto',3);

INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Heredia',4);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Barva',4);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Santo Domingo',4);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Santa Barbara',4);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'San Rafael',4);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'San Isidro',4);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Belen',4);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Flores',4);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'San Pablo',4);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Sarapiqui',4);

INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Limon',5);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Pococi',5);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Siquirres',5);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Talamanca',5);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Matina',5);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Guacimo',5);

INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Puntarenas',6);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Esparza',6);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Buenos Aires',6);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Montes de Oro',6);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Osa',6);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Quepos',6);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Golfito',6);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Coto Brus',6);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Parrita',6);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Corredores',6);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Garabito',6);

INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'San Jose',7);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Escazu',7);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Desamparados',7);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Puriscal',7);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Tarrazu',7);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Aserri',7);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Mora',7);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Goicoechea',7);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Santa Ana',7);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Alajuelita',7);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Vazquez de Coronado',7);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Acosta',7);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Tibas',7);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Moravia',7);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Montes de Oca',7);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Turrubares',7);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Dota',7);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Curridabat',7);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Perez Zeledon',7);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Loen Cortes Castro',7);

INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Cartago',8);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Paraiso',8);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'La Union',8);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Jimenez',8);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Turrialba',8);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Alvarado',8);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'Oreamuno',8);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (3, 'El Guarco',8);

INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (4, 'Carmen',63);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (4, 'Merced',63);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (4, 'Hospital',63);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (4, 'San Francisco de dos rios',63);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (4, 'La Uuruca',63);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (4, 'Mata Redonda',63);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (4, 'Pavas',63);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (4, 'Hatillo',63);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (4, 'San Sebastian',63);

INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (4, 'San Miguel',64);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (4, 'San Antonio',64);
INSERT INTO Geografia (TIPO_GEOGRAFIA, NOMBRE, PADRE) VALUES (4, 'San Rafael',64);