USE [BANK]
GO


CREATE TABLE [dbo].[REGISTRO_ESTADO](
	[UUID] [int] IDENTITY(1,1) NOT NULL,
	[Fecha_Ingreso] date DEFAULT GETDATE(),
	[Descripcion] NVARCHAR(200) NOT NULL,
    [Persona] INT REFERENCES PERSONA(UUID),
	CONSTRAINT [PK_REGISTRO_ESTADO] PRIMARY KEY CLUSTERED
        (
            [UUID] ASC
        )   WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
        ) ON [PRIMARY] --Luego se especifica a que FG ir� segun modelo f�sico
GO

INSERT INTO REGISTRO_ESTADO (DESCRIPCION, PERSONA) VALUES ('USUARIO EN ESTADO ACTIVO',1);
INSERT INTO REGISTRO_ESTADO (DESCRIPCION, PERSONA) VALUES ('USUARIO EN ESTADO Activo',1);
INSERT INTO REGISTRO_ESTADO (DESCRIPCION, PERSONA) VALUES ('USUARIO EN ESTADO Activo',2);
INSERT INTO REGISTRO_ESTADO (DESCRIPCION, PERSONA) VALUES ('USUARIO EN ESTADO Activo',3);
INSERT INTO REGISTRO_ESTADO (DESCRIPCION, PERSONA) VALUES ('USUARIO EN ESTADO Activo',4);
INSERT INTO REGISTRO_ESTADO (DESCRIPCION, PERSONA) VALUES ('USUARIO EN ESTADO Activo',5);
INSERT INTO REGISTRO_ESTADO (DESCRIPCION, PERSONA) VALUES ('USUARIO EN ESTADO Activo',6);
INSERT INTO REGISTRO_ESTADO (DESCRIPCION, PERSONA) VALUES ('USUARIO EN ESTADO Activo',7);
INSERT INTO REGISTRO_ESTADO (DESCRIPCION, PERSONA) VALUES ('USUARIO EN ESTADO Activo',8);
INSERT INTO REGISTRO_ESTADO (DESCRIPCION, PERSONA) VALUES ('USUARIO EN ESTADO Activo',9);
INSERT INTO REGISTRO_ESTADO (DESCRIPCION, PERSONA) VALUES ('USUARIO EN ESTADO Activo',10);
INSERT INTO REGISTRO_ESTADO (DESCRIPCION, PERSONA) VALUES ('USUARIO EN ESTADO Activo',11);
INSERT INTO REGISTRO_ESTADO (DESCRIPCION, PERSONA) VALUES ('USUARIO EN ESTADO Activo',12);
INSERT INTO REGISTRO_ESTADO (DESCRIPCION, PERSONA) VALUES ('USUARIO EN ESTADO Activo',13);
INSERT INTO REGISTRO_ESTADO (DESCRIPCION, PERSONA) VALUES ('USUARIO EN ESTADO Activo',14);
INSERT INTO REGISTRO_ESTADO (DESCRIPCION, PERSONA) VALUES ('USUARIO EN ESTADO Activo',15);
INSERT INTO REGISTRO_ESTADO (DESCRIPCION, PERSONA) VALUES ('USUARIO EN ESTADO Activo',16);
INSERT INTO REGISTRO_ESTADO (DESCRIPCION, PERSONA) VALUES ('USUARIO EN ESTADO Activo',17);
INSERT INTO REGISTRO_ESTADO (DESCRIPCION, PERSONA) VALUES ('USUARIO EN ESTADO Activo',18);
INSERT INTO REGISTRO_ESTADO (DESCRIPCION, PERSONA) VALUES ('USUARIO EN ESTADO Activo',19);
INSERT INTO REGISTRO_ESTADO (DESCRIPCION, PERSONA) VALUES ('USUARIO EN ESTADO Activo',20);
INSERT INTO REGISTRO_ESTADO (DESCRIPCION, PERSONA) VALUES ('USUARIO EN ESTADO Activo',21);
INSERT INTO REGISTRO_ESTADO (DESCRIPCION, PERSONA) VALUES ('USUARIO EN ESTADO Activo',22);
INSERT INTO REGISTRO_ESTADO (DESCRIPCION, PERSONA) VALUES ('USUARIO EN ESTADO Activo',23);
INSERT INTO REGISTRO_ESTADO (DESCRIPCION, PERSONA) VALUES ('USUARIO EN ESTADO Activo',24);
INSERT INTO REGISTRO_ESTADO (DESCRIPCION, PERSONA) VALUES ('USUARIO EN ESTADO Activo',25);
INSERT INTO REGISTRO_ESTADO (DESCRIPCION, PERSONA) VALUES ('USUARIO EN ESTADO Activo',26);
INSERT INTO REGISTRO_ESTADO (DESCRIPCION, PERSONA) VALUES ('USUARIO EN ESTADO Activo',27);
INSERT INTO REGISTRO_ESTADO (DESCRIPCION, PERSONA) VALUES ('USUARIO EN ESTADO Activo',28);
INSERT INTO REGISTRO_ESTADO (DESCRIPCION, PERSONA) VALUES ('USUARIO EN ESTADO Activo',29);
INSERT INTO REGISTRO_ESTADO (DESCRIPCION, PERSONA) VALUES ('USUARIO EN ESTADO Activo',30);
INSERT INTO REGISTRO_ESTADO (DESCRIPCION, PERSONA) VALUES ('USUARIO EN ESTADO Activo',31);
INSERT INTO REGISTRO_ESTADO (DESCRIPCION, PERSONA) VALUES ('USUARIO EN ESTADO Activo',32);
INSERT INTO REGISTRO_ESTADO (DESCRIPCION, PERSONA) VALUES ('USUARIO EN ESTADO Activo',33);
INSERT INTO REGISTRO_ESTADO (DESCRIPCION, PERSONA) VALUES ('USUARIO EN ESTADO Activo',34);
INSERT INTO REGISTRO_ESTADO (DESCRIPCION, PERSONA) VALUES ('USUARIO EN ESTADO Activo',35);
INSERT INTO REGISTRO_ESTADO (DESCRIPCION, PERSONA) VALUES ('USUARIO EN ESTADO Activo',36);
INSERT INTO REGISTRO_ESTADO (DESCRIPCION, PERSONA) VALUES ('USUARIO EN ESTADO Activo',37);
INSERT INTO REGISTRO_ESTADO (DESCRIPCION, PERSONA) VALUES ('USUARIO EN ESTADO Activo',38);
INSERT INTO REGISTRO_ESTADO (DESCRIPCION, PERSONA) VALUES ('USUARIO EN ESTADO Activo',39);
INSERT INTO REGISTRO_ESTADO (DESCRIPCION, PERSONA) VALUES ('USUARIO EN ESTADO Activo',40);
INSERT INTO REGISTRO_ESTADO (DESCRIPCION, PERSONA) VALUES ('USUARIO EN ESTADO Activo',41);
INSERT INTO REGISTRO_ESTADO (DESCRIPCION, PERSONA) VALUES ('USUARIO EN ESTADO Activo',42);
INSERT INTO REGISTRO_ESTADO (DESCRIPCION, PERSONA) VALUES ('USUARIO EN ESTADO Activo',43);
INSERT INTO REGISTRO_ESTADO (DESCRIPCION, PERSONA) VALUES ('USUARIO EN ESTADO Activo',44);
INSERT INTO REGISTRO_ESTADO (DESCRIPCION, PERSONA) VALUES ('USUARIO EN ESTADO Activo',45);
INSERT INTO REGISTRO_ESTADO (DESCRIPCION, PERSONA) VALUES ('USUARIO EN ESTADO Activo',46);
INSERT INTO REGISTRO_ESTADO (DESCRIPCION, PERSONA) VALUES ('USUARIO EN ESTADO Activo',47);
INSERT INTO REGISTRO_ESTADO (DESCRIPCION, PERSONA) VALUES ('USUARIO EN ESTADO Activo',48);
INSERT INTO REGISTRO_ESTADO (DESCRIPCION, PERSONA) VALUES ('USUARIO EN ESTADO Activo',49);
INSERT INTO REGISTRO_ESTADO (DESCRIPCION, PERSONA) VALUES ('USUARIO EN ESTADO Activo',50);