USE [BANK]
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Garantia_Operacion](
	[UUID] [int] IDENTITY(1,1) NOT NULL,
	[Operacion] INT REFERENCES OPERACION(UUID) NOT NULL,
	[Garantia] INT REFERENCES GARANTIA(UUID) NOT NULL,
	CONSTRAINT UNIQUE_GARANTIA_OPERACION UNIQUE(OPERACION, GARANTIA),
	CONSTRAINT [PK_Garantia_Operacion] PRIMARY KEY CLUSTERED
(
	[UUID] ASC, 
	[OPERACION] ASC,
	[GARANTIA] ASC
)	WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) 	ON [PRIMARY]
GO

Create view view_Garantia_Operacion(
	UUID,
	Descripcion
) AS
SELECT
	UUID,
	Descripcion
FROM
	Garantia
GO


--Ejemplo 
INSERT INTO GARANTIA_OPERACION VALUES(1,1)
INSERT INTO GARANTIA_OPERACION VALUES(2,2)
INSERT INTO GARANTIA_OPERACION VALUES(3,3)
INSERT INTO GARANTIA_OPERACION VALUES(4,4)
INSERT INTO GARANTIA_OPERACION VALUES(5,5)
INSERT INTO GARANTIA_OPERACION VALUES(6,6)
INSERT INTO GARANTIA_OPERACION VALUES(7,7)
INSERT INTO GARANTIA_OPERACION VALUES(8,8)
INSERT INTO GARANTIA_OPERACION VALUES(9,9)
INSERT INTO GARANTIA_OPERACION VALUES(10,10)
INSERT INTO GARANTIA_OPERACION VALUES(11,11)
INSERT INTO GARANTIA_OPERACION VALUES(12,12)
INSERT INTO GARANTIA_OPERACION VALUES(13,13)
INSERT INTO GARANTIA_OPERACION VALUES(14,14)
INSERT INTO GARANTIA_OPERACION VALUES(15,15)
INSERT INTO GARANTIA_OPERACION VALUES(16,16)
INSERT INTO GARANTIA_OPERACION VALUES(17,17)
INSERT INTO GARANTIA_OPERACION VALUES(18,18)
INSERT INTO GARANTIA_OPERACION VALUES(19,19)
INSERT INTO GARANTIA_OPERACION VALUES(20,20)
INSERT INTO GARANTIA_OPERACION VALUES(21,21)
INSERT INTO GARANTIA_OPERACION VALUES(22,22)
INSERT INTO GARANTIA_OPERACION VALUES(23,23)
INSERT INTO GARANTIA_OPERACION VALUES(24,24)
INSERT INTO GARANTIA_OPERACION VALUES(25,25)
INSERT INTO GARANTIA_OPERACION VALUES(26,26)
INSERT INTO GARANTIA_OPERACION VALUES(27,27)
INSERT INTO GARANTIA_OPERACION VALUES(28,28)
INSERT INTO GARANTIA_OPERACION VALUES(29,29)
INSERT INTO GARANTIA_OPERACION VALUES(30,30)
INSERT INTO GARANTIA_OPERACION VALUES(31,31)
INSERT INTO GARANTIA_OPERACION VALUES(32,32)
INSERT INTO GARANTIA_OPERACION VALUES(33,33)
INSERT INTO GARANTIA_OPERACION VALUES(34,34)
INSERT INTO GARANTIA_OPERACION VALUES(35,35)
INSERT INTO GARANTIA_OPERACION VALUES(36,36)
INSERT INTO GARANTIA_OPERACION VALUES(37,37)
INSERT INTO GARANTIA_OPERACION VALUES(38,38)
INSERT INTO GARANTIA_OPERACION VALUES(39,39)
INSERT INTO GARANTIA_OPERACION VALUES(40,40)
INSERT INTO GARANTIA_OPERACION VALUES(41,41)
INSERT INTO GARANTIA_OPERACION VALUES(42,42)
INSERT INTO GARANTIA_OPERACION VALUES(43,43)
INSERT INTO GARANTIA_OPERACION VALUES(44,44)
INSERT INTO GARANTIA_OPERACION VALUES(45,45)
INSERT INTO GARANTIA_OPERACION VALUES(46,46)
INSERT INTO GARANTIA_OPERACION VALUES(47,47)
INSERT INTO GARANTIA_OPERACION VALUES(48,48)